# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

strategy:
  matrix:
    linux:
      platform: 'linux'
      imageName: 'ubuntu-latest'
    mac:
      platform: 'macos'
      imageName: 'macos-latest'
    windows:
      platform: 'win'
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- bash: npm install -g license-checker pkg
  displayName: 'Install additional build tools'

- bash: ./build-examples.sh
  displayName: 'Build examples'

- publish: $(System.DefaultWorkingDirectory)/export
  artifact: etcher-sdk-examples-$(platform)
